CREATE TABLE users (
    UID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    RFID VARCHAR(255) NOT NULL,
    Balance DECIMAL(10,2) DEFAULT 10.00,
    Username VARCHAR(255) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    role VARCHAR(255) DEFAULT 'user'
);
